### ISSUE TITLE
Artie doesn't start at all

### ISSUE THREAD

**Issue by YoMama78** [milouk/artie#12]
I added username and password. As  a contributing member I also changed "threads" to 6. 
When I try to start Artie all I get is "Loading Application" and nothing happens.

Log:
Traceback (most recent call last):
  File "app.py", line 611, in <module>
  File "app.py", line 100, in start
  File "app.py", line 84, in load_config
  File "app.py", line 288, in get_user_threads
TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'
[PYI-28348:ERROR] Failed to execute script 'app' due to unhandled exception!

Device: RG40XX V / MuOS Banana

**Comment by milouk** [comment]
Do you still have the issue?

**Comment by YoMama78** [comment]
> Do you still have the issue?

No, with version 1.0.5 every thing works fine, thank you!
