### ISSUE TITLE
Stucked at "scraping...."

### ISSUE THREAD

**Issue by Vendo233** [milouk/artie#6]
Hi
I`m testing your scraper, followwed your guide and the unit gets stocked ( needs reboot ) when I selec one or multiple games to scrape.
My ROMS are on MMC card , do not have 2nd SC CARD

![image](https://github.com/user-attachments/assets/ae2f7cbd-98ac-49ef-8648-c6f3522466a0)

![image](https://github.com/user-attachments/assets/3f36a14a-694b-40fe-9047-c6f653d234a2)

**Comment by milouk** [comment]
Can you post the context of `log.txt` located in `.artie/` . Be sure to remove any sensitive data.

**Comment by Vendo233** [comment]
Traceback (most recent call last):
  File "app.py", line 585, in <module>
  File "app.py", line 96, in update
  File "app.py", line 385, in load_roms
  File "app.py", line 243, in scrape
  File "scraper.py", line 139, in find_game
  File "scraper.py", line 74, in parse_find_game_url
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbd in position 0: invalid start byte
[PYI-3444:ERROR] Failed to execute script 'app' due to unhandled exception!

**Comment by milouk** [comment]
ok, thank you, i will have to look into that

**Comment by Vendo233** [comment]
any update?

**Comment by milouk** [comment]
I will have an update the following days

**Comment by milouk** [comment]
Uploaded a new version. Please try to see if it fixes your issue. If it doesn't please send me the log.txt (remove any sensitive info)

**Comment by milouk** [comment]
i forgot to update the header. Please use "debug" in  log level in the config.json file instead of info and check again the log.txt

**Comment by Vendo233** [comment]
I did changed the into to debug but the log file remains empty

**Comment by Vendo233** [comment]
iT

**Comment by Vendo233** [comment]
IT WORKS NOW, had to reboot device.

**Comment by Vendo233** [comment]
Do you guys know all the available options apart from box-3D?

"box": {
        "enabled": true,
        "type": "**_box-3D_**",
        "height": 240,
        "width": 320

**Comment by milouk** [comment]
```
bezel-16-9-cocktail
bezel-16-9
bezel-16-9-v
bezel-4-3-cocktail
bezel-4-3
bezel-4-3-v
box-3D
box-texture
box-2D-back
box-2D
box-2D-side
wheel-hd
wheel
wheel-carbon
wheel-steel
fanart
flyer
manuel
maps
marquee
screenmarqueesmall
overlay
screenmarquee
ss
sstitle
steamgrid
themehs
video
video-normalized
ssdmd
ssfronton16-9
ssfronton1-1
ssfronton4-3
sstable
sstopper
videodmd
videofronton4-3
videofronton16-9
videotable4k
videotable
videotopper
wheel-tarcisios
mixrbv1
mixrbv2
box-scan
support-scan
support-2D
support-texture
```

**Comment by dirn** [comment]
> Do you guys know all the available options apart from box-3D?
> 
> "box": { "enabled": true, "type": "**_box-3D_**", "height": 240, "width": 320

@Vendo233 this seems to be what's supported https://github.com/milouk/artie/blob/f0a0103162d416ca5eaa0b4ba07a6623c68bdda7/src/scraper.py#L16
